import type { Role } from "@circular-city/contracts";

export interface RoleQuizQuestion {
  question: string;
  choices: readonly [string, string, string, string];
  correctChoiceIndex: number;
}

const question = (
  prompt: string,
  choices: RoleQuizQuestion["choices"],
  correctChoiceIndex: number,
): RoleQuizQuestion => ({ question: prompt, choices, correctChoiceIndex });

export const ROLE_QUIZ_QUESTIONS: Record<Role, readonly RoleQuizQuestion[]> = {
  municipality: [
    question("What pricing system charges residents by the weight or volume of trash to encourage less waste?", ["Flat property taxes", "Pay-As-You-Throw (PAYT)", "Landfill surcharges", "Carbon pricing"], 1),
    question("Why might a city update zoning laws to allow repair shops and tool libraries?", ["To speed up disposal", "To encourage sharing and reuse", "To increase landfill volume", "To promote heavy manufacturing"], 1),
    question("How do cities typically collaborate with Extended Producer Responsibility programs?", ["By paying manufacturing costs", "By banning producer sales", "By sharing collection and receiving producer funding", "By taking full legal blame for packaging"], 2),
    question("Why do cities mandate source separation of recyclables?", ["To maintain purity and market value", "To feed incinerators faster", "To eliminate garbage trucks", "To collect fines"], 0),
    question("What is an example of Green Public Procurement by a city?", ["Buying cheap virgin plastics", "Requiring recycled materials in public construction", "Expanding commuter parking lots", "Removing environmental checks"], 1),
    question("Why is organic-waste diversion important for a circular city?", ["It turns waste into new plastics", "It returns nutrients to soils and farms", "It replaces wastewater plants", "It powers metal factories"], 1),
    question("How do municipal public education campaigns support circular economies?", ["By teaching planned obsolescence", "By lowering recycling contamination", "By forcing brand loyalty", "By replacing sorting machines"], 1),
    question("What does urban mining mean in circular municipal management?", ["Digging for coal under streets", "Recovering materials from old buildings and e-waste", "Mining rare minerals in parks", "Hauling trash to open-pit mines"], 1),
    question("What is a major challenge in decentralized circular waste systems?", ["Excess free workers", "Balancing new investments with old disposal contracts", "Total disappearance of waste", "International composting bans"], 1),
    question("How can building codes support circular construction?", ["Require demolition every decade", "Mandate salvage and recovery plans before demolition", "Ban reclaimed wood and steel", "Subsidize single-use materials"], 1),
    question("What metric commonly measures circular waste success?", ["Raw material imports", "Municipal solid-waste diversion rate", "Garbage truck speed", "Streetlight electricity use"], 1),
    question("What is the primary purpose of a municipal waste transfer station?", ["Permanently store hazardous chemicals", "Consolidate loads into larger trucks", "Burn unsorted garbage", "Operate a retail reuse market"], 1),
    question("How do municipal single-use plastic bans support circular systems?", ["Tax paper bags heavily", "Remove hard-to-recycle items at the source", "Force citizens to manufacture containers", "Increase landfill packaging"], 1),
    question("What is a key advantage of inter-municipal waste cooperation?", ["Sharing costs for advanced sorting technology", "Secret dumping in other towns", "Changing national tax laws", "Ignoring environmental rules"], 0),
    question("How can cities integrate informal waste pickers into formal systems?", ["Make informal collection illegal", "Provide registration, safety gear, and integration", "Lower aluminum values", "Outsource to shipping firms"], 1),
    question("Why do cities host hazardous-waste drop-off sites?", ["Give free supplies to corporations", "Prevent toxic materials polluting recycling streams", "Manufacture new pesticides", "Collect food scraps for feed"], 1),
    question("How do circular city plans handle textile waste?", ["Bury clothes in vaults", "Partner with reuse charities for collection bins", "Ban owning more than five outfits", "Burn textiles for heating"], 1),
    question("What is a Circular City Roadmap?", ["A landfill-location map", "A long-term plan for zero-waste targets and policies", "An electric-bus route map", "A zoning plan banning commerce"], 1),
    question("How do circular policies influence local startups?", ["Offer grants and testing space for repair and upcycling", "Place heavy taxes on services", "Ban recycled materials", "Force linear models"], 0),
    question("What major problem does wish-cycling cause?", ["Citizens recycle too efficiently", "It jams sorters and ruins batch purity", "It lowers collection costs", "It stops composting"], 1),
    question("How can wastewater plants support a circular water system?", ["Pump raw sewage onto farms", "Reclaim water and extract nutrients such as phosphorus", "Evaporate water for salt", "Turn wastewater into fossil fuels"], 1),
    question("What is the purpose of municipal eco-labels or certifications?", ["Prove eco-friendly features for consumer choices", "Penalize sustainable businesses", "Guarantee linear extraction", "Replace safety laws"], 0),
    question("How do public-private partnerships help circular infrastructure?", ["Let firms ignore laws", "Combine municipal authority with private funding and expertise", "Turn parks into parking", "Push all risk onto taxpayers"], 1),
    question("Why is lifecycle thinking important for procurement contracts?", ["Evaluate durability and end-of-life recovery, not only upfront price", "Ensure equipment breaks after warranty", "Stop buying metal products", "Block local suppliers"], 0),
    question("How can circular policies address brownfields?", ["Fence them off permanently", "Clean and repurpose them as circular hubs or solar arrays", "Turn them into new dumps", "Ignore pollution"], 1),
    question("What is the purpose of a municipal waste composition audit?", ["Fine individual households", "Sample waste to assess recovery and contamination", "Check tax records", "Sort metal on streets"], 1),
    question("How do cities support tool-sharing networks?", ["Fund or provide space/logistics for sharing infrequent items", "Require many duplicate tool sets", "Tax sharing groups", "Ban hand tools"], 0),
    question("Why must municipal bylaws align with national or state frameworks?", ["Ensure legal consistency and streamline regional supply chains", "Ignore environmental protection", "Make random rules", "Eliminate local collection"], 0),
    question("How do municipal circular strategies handle electronic waste?", ["Put computers in regular trash", "Run e-waste drives with certified recyclers", "Ship electronics overseas unverified", "Discourage device use"], 1),
    question("What is the ultimate goal of a circular urban ecosystem?", ["Stop all human activity", "Decouple growth from virgin resources by closing loops and regenerating nature", "Maximize landfill fees", "Cut off all regional trade"], 1),
  ],
  mrf: [
    question("What is the primary function of an MRF?", ["Garbage collection", "Sorting, cleaning, and baling recyclables", "Manufacturing consumer goods", "Setting waste laws"], 1),
    question("What distinguishes a clean MRF from a dirty MRF?", ["Hazardous versus organic handling", "Source-separated versus mixed waste processing", "Robotic versus manual labor", "Indoor versus outdoor facilities"], 1),
    question("Which device extracts ferrous metals such as steel cans?", ["Eddy current separator", "Optical sorter", "Overband magnet", "Air classifier"], 2),
    question("How are non-ferrous metals such as aluminum separated?", ["Eddy current separator", "UV scanner", "Manual sorting", "Chemical bath"], 0),
    question("What is the main purpose of optical sorters?", ["Compressing bales", "Identifying plastics and paper with infrared light", "Removing glass shards", "Weighing trucks"], 1),
    question("What does a trommel screen do?", ["Melts plastics", "Separates items by size", "Shreds cardboard", "Compacts waste"], 1),
    question("What is residue at an MRF?", ["High-grade aluminum", "Non-recyclable material sent to landfill", "Plastic washwater", "Baled cardboard"], 1),
    question("Why is contamination control critical at an MRF?", ["To meet buyer purity standards", "To speed up trucks", "To lower insurance", "To remove magnets"], 0),
    question("What is the main purpose of baling?", ["Hiding defects", "Compressing material for transport and sale", "Preparing for landfill", "Cooling machinery"], 1),
    question("What is a ballistic separator used for?", ["Separating 2D from 3D items", "Crushing glass", "Detecting radiation", "Sorting e-waste"], 0),
    question("Why are glass containers handled carefully at an MRF?", ["They are too light to sort", "They cause abrasive damage and paper contamination", "They have zero value", "They melt optical lenses"], 1),
    question("What does OCC stand for?", ["Organic Compost Component", "Old Corrugated Cardboard", "Optimized Container", "Out-of-Cycle Collection"], 1),
    question("What problem do plastic film bags cause?", ["Increase aluminum recovery", "Wrap around shafts and cause downtime", "Improve paper quality", "Lubricate belts"], 1),
    question("What is the role of manual sorters?", ["Designing bins", "Removing large contaminants and dangerous items", "Negotiating broker prices", "Driving trucks"], 1),
    question("What is an air classifier used for?", ["Separating lightweight items with air streams", "Cooling motors", "Testing room air", "Removing glass dust"], 0),
    question("What is a bale specification?", ["A dumping permit", "Standards for bale weight, density, and purity", "An MRF blueprint", "A zoning rule"], 1),
    question("How do MRFs track operational efficiency?", ["Recovery rates, throughput, and loss percentages", "Daily employee count", "City population growth", "Weather patterns"], 0),
    question("Why do commodity prices experience volatility?", ["Daily law changes", "Global supply, demand, and virgin-material price shifts", "Seasonal breakdowns", "Paper decay"], 1),
    question("What is a secondary sort line used for?", ["Polishing streams for maximum purity", "Dumping waste", "Washing trucks", "Staff training"], 0),
    question("What is a major limitation of optical sorting?", ["Needs dark rooms", "Struggles with dark, black, or soiled plastics", "Only works on organics", "Requires water immersion"], 1),
    question("How are hazardous items such as batteries handled?", ["Melted with plastics", "Manually extracted during pre-sort", "Shipped to paper mills", "Ignored"], 1),
    question("What is throughput?", ["Profit per ton", "Total volume processed over time", "Landfill percentage", "Truck highway speed"], 1),
    question("What is the difference between PET and HDPE?", ["Glass versus metal", "Different polymer resin types needing separate sorting", "Organic versus inorganic", "Hazardous versus inert"], 1),
    question("Why is moisture control important for paper?", ["Wet paper ruins fiber quality and lowers value", "It causes electrical fires", "It speeds optical sorters", "It increases bale weight"], 0),
    question("How do eddy current rotors work?", ["Gravity drops", "Rotating fields induce currents that repel non-ferrous metals", "Freezing aluminum", "Suction fans"], 1),
    question("What is a primary financial risk for private MRFs?", ["Water shortage", "Falling commodity prices plus high contamination", "Overstaffing", "Landscaping rules"], 1),
    question("How does an MRF bridge municipalities and brokers?", ["Shipping retail goods", "Turning messy waste into clean commodities for trade", "Setting national taxes", "Auditing household cans"], 1),
    question("What is wish-cycling?", ["Recycling too much aluminum", "Tying trash to bikes", "Putting unrecyclables in bins and creating sorting hazards", "Cleaning bottles too well"], 2),
    question("What is the goal of densifying materials?", ["Making bales heavier for dumps", "Reducing shipping volume and freight costs", "Changing chemical makeup", "Dissolving materials"], 1),
    question("What role do AI and robotics play in modern MRFs?", ["Replacing administrative staff", "Powering robotic arms for fast, precise sorting", "Driving autonomous trucks", "Replacing electricity"], 1),
  ],
  broker: [
    question("What is the primary role of a broker in the recycling supply chain?", ["Collecting garbage", "Sorting mixed waste", "Connecting suppliers with global buyers", "Enforcing zoning laws"], 2),
    question("How do brokers help MRFs manage market risks?", ["Buying machinery", "Securing contracts and hedging volatility", "Paying municipal taxes", "Taking collection routes"], 1),
    question("What does price discovery mean in secondary commodity trading?", ["Finding hidden bin items", "Determining fair market value from supply and demand", "Setting collection fees", "Valuing real estate"], 1),
    question("Why are international waste-trade regulations critical for brokers?", ["Setting ship speeds", "Ensuring legal, sound cross-border trade", "Dictating landfill taxes", "Banning recycling"], 1),
    question("What happens when a buyer rejects a high-contamination shipment?", ["Arbitrate disputes and negotiate re-grading", "Burn it immediately", "Jail the municipality", "Force a shipping company to buy a factory"], 0),
    question("What is a spot market in secondary commodities?", ["A used-goods retail store", "Immediate trading at current daily prices", "A hazardous-waste site", "A storage yard"], 1),
    question("How do brokers provide market intelligence to processing facilities?", ["Testing water", "Sharing high-demand material trends", "Auditing households", "Designing robots"], 1),
    question("Why do brokers need freight-logistics knowledge?", ["Driving every truck", "Managing multi-mode freight cost-effectively", "Bypassing weigh stations", "Avoiding insurance"], 1),
    question("What drives recycled-plastic commodity volatility?", ["Daily weather", "Virgin petroleum price and demand fluctuations", "City elections", "Paper-mill capacity"], 1),
    question("What is a letter of credit in international trade?", ["A school certificate", "A bank guarantee after shipping proof", "A dumping permit", "A cardboard coupon"], 1),
    question("How do brokers handle currency-exchange risk?", ["Refuse foreign currency", "Use hedging and multi-currency contracts", "Pay only in gold", "Rely on local laws"], 1),
    question("Why might a broker advise an MRF to upgrade sorting technology?", ["Increase noise", "Meet strict mill purity specifications", "Consume more electricity", "Slow production"], 1),
    question("What is the key difference between a broker and an MRF?", ["Commerce/logistics versus physical sorting", "City workers versus individuals", "Hazardous versus paper handling", "No difference"], 0),
    question("What is contamination arbitration?", ["Settling property disputes", "Resolving purity and grading disagreements", "Testing landfill water", "Fining residents"], 1),
    question("Why is OCC demand tied to e-commerce?", ["More shipping-box volume for mills", "Cardboard powers vans", "Retailers burn it for heat", "Shoppers recycle plastics"], 0),
    question("How do brokers reduce buyer-default risk?", ["Trust blindly", "Conduct credit checks and use secure terms", "Withhold tracking numbers", "Demand cash in person"], 1),
    question("What do brokers do as liquidity catalysts?", ["Melt plastic", "Maintain steady material flow between supply and demand", "Manage water plants", "Pump landfill oil"], 1),
    question("What is a broker's customs-clearance responsibility?", ["Inspecting engines", "Managing documentation, tariffs, and compliance", "Collecting park taxes", "Weighing drivers"], 1),
    question("Why do some countries ban imported scrap plastics?", ["Protect ecosystems from unrecyclable waste", "Encourage plastic purchases", "Increase shipping cost", "Eliminate manufacturing"], 0),
    question("How do brokers use intermodal transport?", ["Ship small local boxes", "Move bulk volumes efficiently long-distance", "Bypass laws", "Store material indefinitely"], 1),
    question("What is a material broker's primary revenue source?", ["Property taxes", "Commissions, margins, or logistics fees", "Tipping fees", "Government subsidies"], 1),
    question("How do economic downturns affect secondary commodity brokers?", ["Mill demand drops and prices crash", "Demand increases exponentially", "Nothing changes", "Shipping becomes free"], 0),
    question("What is feedstock in material brokerage?", ["Animal food", "Raw secondary material supplied to mills", "Truck fuel", "Grid electricity"], 1),
    question("Why verify bale weights and moisture levels?", ["Prevent disputes and meet transport limits", "Check waterproof plastic", "Calculate population", "Predict weather"], 0),
    question("What is a long-term supply contract?", ["A neighbor promise", "A fixed-volume structured agreement over time", "A daily spot trade", "A warehouse lease"], 1),
    question("How do brokers support closed-loop manufacturing?", ["Find reliable recycled inputs", "Encourage virgin plastics", "Destroy used products", "Block trade"], 0),
    question("What is triangular trade in secondary commodities?", ["Triangle-shaped boxes", "Direct shipping managed from a third hub", "Recycling three metals", "Trading between three cities"], 1),
    question("Why is transparent MRF-broker communication vital?", ["Hide trade secrets", "Align expectations on volume and quality", "Eliminate contracts", "Set property taxes"], 1),
    question("How do regional trade agreements affect brokerages?", ["Simplify logistics and reduce tariffs", "Ban material movement", "Replace brokers with government workers", "Eliminate shipping"], 0),
    question("What is the ultimate economic function of brokers in a circular system?", ["Match supply and demand to maximize resource value", "Dispose of waste in oceans", "Eliminate recycling facilities", "Control water supplies"], 0),
  ],
};
